### ISSUE TITLE
[MISC] Mapbase not changing chapter name 

### ISSUE THREAD

**Issue by DrRetro2033** [mapbase-source/source-sdk-2013#135]
I have been working on a mod that is using Mapbase as a base for, and I want to name the chapters. [I did everything the this guide said](https://developer.valvesoftware.com/wiki/Adding_chapters_to_your_mod) but it is not working and every chapter is named #mapbase_hl2_Chapter( the chapter's number)_Title and I am sick and tired of this. It may just be my problem that I caused and has nothing to do with Mapbase, but I want to make sure that if is a problem with Mapbase, it can be fixed.

The Issue:
![Capture](https://user-images.githubusercontent.com/86109384/122557977-7f117400-d00b-11eb-87b8-64cf363b1e98.PNG)

Mapbase's default localization file (This is the one located in mapbase_hl2\content\hl2_mapbase_content_dir.vpk):
[mapbase_hl2_english.txt](https://github.com/mapbase-source/source-sdk-2013/files/6676887/mapbase_hl2_english.txt)

**Comment by Jesse-Culver** [comment]
Have you tried adding your own localization file to your mod and modifying that to include your chapter names?

**Comment by DrRetro2033** [comment]
Yes, I tried everything

**Comment by Jesse-Culver** [comment]
Could you please expand on what you mean by tried everything? We need as much detail as possible to track down the issue.

What setup are you using for Mapbase as well. Are you using the templates provided on ModDB or are you packing everything into your own mod?

**Comment by DrRetro2033** [comment]
The ModDB Release, Ver 6.3

**Comment by DrRetro2033** [comment]
And I tried to rename the localization file to hl2, My mods name in the gameinfo file, mapbase, mapbase_hl2, and none of them work. I know that it is the localization file because I tried to rename one of the achievements that are in hl2 and it also did not work.

**Comment by Blixibon** [comment]
The engine automatically names chapter localization tokens based on the name of the mod's folder. Since the names of these chapters are prefixed with `mapbase_hl2`, that suggests the name of your mod's folder is `mapbase_hl2`. (or at least that's what the engine seems to think)

If you're just modifying `mapbase_hl2` with your own files, that's not how Mapbase is supposed to be used. You are supposed to create your own mod folder which integrates Mapbase's content. If you are already operating from your own mod folder, could you tell us more about how it's set up? What is the name of your mod's folder?

Please read this article on Mapbase's wiki for more information on how to set up a Mapbase mod:
https://github.com/mapbase-source/source-sdk-2013/wiki/Modding-with-Mapbase
