### ISSUE TITLE
[NPCs] RPG aiming

### ISSUE THREAD

**Issue by THG327** [mapbase-source/source-sdk-2013#141]
### Describe the bug
NPC characters such as the rebel citizens in d3_c17_12 cannot properly aim the RPG since they use the laser dot aiming method as if they were a player.
This is likely due to the changes in animation behaviour to prevent SMG animations or something.

### Steps to reproduce
Steps to reproduce the behaviour:
1. Load d3_c17_12
2. Observe as a rocket curves to the left or even back at the citizen.
3. Stare as the resistance is torn apart by their own rockets while the striders roam happily.

### Expected behaviour
NPC characters should not use laser dot aiming since it is supposed to be disabled in CWeaponRPG::Operator_HandleAnimEvent when using the animation event "EVENT_WEAPON_SMG1" (3002)

---

### Additional context
(Optional) Add any other context about the problem here.
![image](https://user-images.githubusercontent.com/88611153/128625526-389976a0-e526-40f7-8146-66fb61898c75.png)

**Comment by THG327** [comment]
The issue isn't really a code issue but an issue with the custom citizen animations not firing the 3002 animevent
 " { event 3002 0 "" } "
The code in Operator_HandleAnimEvent is never called as a result so the NPCs fire using laser aiming.

**Comment by Blixibon** [comment]
After testing, I can confirm that Event 3002 is already called every time a rebel fires an RPG. There does not appear to be any difference between stock citizen animations and Mapbase's citizen animations.

Citizens are designed to use laser dot aiming as of The Orange Box update, but due to a bug with the RPG's LOS code, they normally do not run the required schedules except under special conditions. You can see citizens using the laser dot in the EP2 strider battle. Mapbase fixes the LOS bug, so the required LOS schedules now always run, but that fix is not causing this issue.

After further investigation, it appears that this problem was actually caused by the lack of code which was mistakenly disabled in `CNPC_Citizen::GetActualShootPosition`. That code will be re-enabled for the next Mapbase update.

**Comment by THG327** [comment]
I hope I didn't waste your time with the AnimEvent business too much. Thanks for clarifying and fixing the issue.
