### ISSUE TITLE
[VISUAL] SDK_Core doesnt exist

### ISSUE THREAD

**Issue by valina354** [mapbase-source/source-sdk-2013#238]
### Describe the bug
SDK_core doesnt exist in Shaders.sln and so causes errors

### Steps to reproduce
1. Have 'prop_scalable' or 'prop_coreball' in the map
2. Select coreball.mdl
3. See error

### Expected behavior
Coreball wont render

### Additional context
Error in console:
Material models/props_combine/core_sheet does not support vertex format used by the mesh (maybe missing fields or mismatched vertex compression?), mesh will not be rendered. Grab a programmer!

Works with normal core shader not SDK_core but shows the buggy core

**Comment by valina354** [comment]
I figured it out that its missing from vpc in maplabs, but the core is still broken

**Comment by Blixibon** [comment]
The problem with the core not updating its position turned out to be caused by Mapbase v7.0 shipping with an outdated version of the VMT that had broken material parameters. Inside of the core ball VMT, you can find these parameters:
```
    // Mapbase - New vars to control previously hardcoded values (also see proxies)
    "$spherecenter" "2688.0, 12139.0, 5170.0"
    "$sphereradius" "215.0"
    "$entityorigin" "2688.0, 12139.0, 5170.0"
```
The vectors should actually be enclosed with square brackets:
```
    // Mapbase - New vars to control previously hardcoded values (also see proxies)
    "$spherecenter" "[2688.0, 12139.0, 5170.0]"
    "$sphereradius" "215.0"
    "$entityorigin" "[2688.0, 12139.0, 5170.0]"
```
This will fix the core ball not updating its position.

I will fix this in the next Mapbase update.
