### ISSUE TITLE
Actbusy manifest override is loaded before creation of string register of activities

### ISSUE THREAD

**Issue by stepa2** [mapbase-source/source-sdk-2013#25]
Assertion in server\ai_activity.cpp line 73: `m_pActivitySR` is null
Can be reproduced by loading mapbase_demo01

1. When `IGameSystem::LevelInitPreEntityAllSystems` called, all `LevelInitPreEntity` functions
of all game systems are executed in addition order.
2. `m_pActivitySR` is created by `CAI_SystemHook::LevelInitPreEntity`, 
but it is called after `CMapbaseSystem::LevelInitPreEntity`
3. That function load and registers actbusies from file specified in manifest using `CActBusyAnimData::ParseAnimDataFile`.
4. And `ParseAnimDataFile` uses `CAI_BaseNPC::GetActivityID`, which fails on `Assert( m_pActivitySR );` 

There is also a call of `CActBusyAnimData::ParseAnimDataFile` from `CActBusyAnimData::LevelInitPostEntity`, which loads default ActBusy.txt file without any errors.

**Comment by Blixibon** [comment]
In light of this issue, I'm going to experiment with making manifests load from `LevelInitPostEntity` instead of `LevelInitPreEntity`. This could possibly make sound overrides specified through the manifest system not load in time for, say, `ambient_generic` or entity precaching functions. I consider that a low-priority issue because sound overrides are already loaded automatically through an existing, unaffected system and I don't know anyone who loads additional scripts this way.

Thank you for reporting this.
