### ISSUE TITLE
[GAME] You can't playback different videos with multiple vgui_movie_displays in a single map.

### ISSUE THREAD

**Issue by fulano0esquerda** [mapbase-source/source-sdk-2013#259]
### Describe the bug
If you have multiple vgui_movie_displays in a map set to playback different video files, only one of those videos will play and it will override the rest of the vgui_movie_displays in the map (In other words, all of the other displays will only playback the same video). 
The video that will override the rest of the displays is completely regardless of the order of playback.

![image](https://github.com/mapbase-source/source-sdk-2013/assets/83985990/5d383793-c41c-41ed-9121-05e90fb3910d)

### Expected behavior
Multiple vgui_movie_displays should be able to play multiple different video files in a single map.

### Additional context
I'm unsure if this is a limitation from the Alien Swarm SDK code or an actual bug from Mapbase, given how the VDC never mentions this problem.

**Comment by sitkinator** [comment]
Well, I talked with Shiro about this and he mentioned an interesting workaround.

Put various videos onto one video all at once, and just crop the resolution of the various vgui_movie_displays around the map so that they only show a specific part of it. I'm guessing the biggest disadvantage of it could be the video getting crustier with the lower resolution, but other than that I think it'd be fine.

**Comment by WhiteRedDragons** [comment]
The biggest disadvantage is probably that if you use bink it might be straight up impossible to do, and even if it works the filesize will be bonkers. I can imagine it impacting fps quite hard as well because the files are just _that_ big...
Probably not a concern at all with noodles webm implementation

**Comment by fulano0esquerda** [comment]
> The biggest disadvantage is probably that if you use bink it might be straight up impossible to do, and even if it works the filesize will be bonkers. I can imagine it impacting fps quite hard as well because the files are just _that_ big...
> Probably not a concern at all with noodles webm implementation

This problem has nothing to do with bink  and playing back multiple videos should not hurt the performance, even if their file sizes were big.
Changing my video files to webm changes nothing and it doesn't fix the issue. This is most likely a problem with the entity itself.

**Comment by fulano0esquerda** [comment]
> Well, I talked with Shiro about this and he mentioned an interesting workaround.
> 
> Put various videos onto one video all at once, and just crop the resolution of the various vgui_movie_displays around the map so that they only show a specific part of it. I'm guessing the biggest disadvantage of it could be the video getting crustier with the lower resolution, but other than that I think it'd be fine.

Yeah this is a pretty bad workaround but I guess it will have to work for now

**Comment by SellFace** [comment]
Hello, after doing quick research of this entity I am sure this isn't a bug, because the problem is solved by setting a different "Group name" keyvalue for each entity. Other properties, including targetname may remain the same.
Apparently the override happens only between entities within same group.

![image](https://github.com/mapbase-source/source-sdk-2013/assets/129298866/f86fb3f7-ec8e-44af-93a1-1a403c76ea46)

**Comment by fulano0esquerda** [comment]
Wow thanks! I wish there was a better documentation on the differences in Mapbase's backported entities
