### ISSUE TITLE
The logo at the top of the wiki doesn't display.

### ISSUE THREAD

**Issue by MesaBlack** [mapbase-source/source-sdk-2013#267]
![image](https://github.com/mapbase-source/source-sdk-2013/assets/132141735/5d85025c-c1e8-43e5-a828-70fb560ef1cc)

**Comment by Blixibon** [comment]
It shows up on my end. Are you still experiencing this problem?

**Comment by Employee8** [comment]
I also can't see it, accessing the [img url](https://camo.githubusercontent.com/a77d5873fbaa48fa4595746418c79be793f38d3d2d2dd3441d56b3200712ed8b/68747470733a2f2f692e696d6775722e636f6d2f75304b784f69502e706e67) shows Bad Signature

**Comment by MesaBlack** [comment]
> It shows up on my end. Are you still experiencing this problem?

yes. you must've had the image hosted somewhere. isn't it somewhere in the files?

**Comment by Blixibon** [comment]
I investigated this issue and discovered that the home page on the wiki used a temporary GitHub image link instead of the original image link from the Media Resources page.

I've swapped it out and it should now work properly. Please leave another comment here if anyone continues to have problems with the image.
