### ISSUE TITLE
[CODE] This is related to shaders, missing .fxc shaders

### ISSUE THREAD

**Issue by valina354** [mapbase-source/source-sdk-2013#277]
### Describe the bug
I was trying to port vertexlit lightmaps from MP to SP and while porting stuff related to .fxc i found that SDK_vertexlit_and_unlit_generic_ps30.fxc and SDK_vertexlit_and_unlit_generic_vs30.fxc, the .inc are there but not the .fxc

### Steps to reproduce
1. Download Mapbase Source Code
2. Look In materialsystem
3. See theres missing .fxc

### Expected behavior
The .fxc are missing

### Additional context
Shaders look for both of the files so that means the .fxc shouldnt be missing
![image](https://github.com/mapbase-source/source-sdk-2013/assets/80889633/040f2650-ea0b-4459-9f3c-c1483c00b4f7)

**Comment by Blixibon** [comment]
There is no specific file for `ps30`/`vs30`. Using the shader collection text files, the shader compiler compiles `SDK_vertexlit_and_unlit_generic_ps20b` into `ps20b` *and* `ps30`. The same is done with `SDK_vertexlit_and_unlit_generic_vs20`, which compiles into `vs20` and `vs30`.

I'm also pretty sure that vertex lit lightmaps can't be ported from MP to SP due to relying on MP engine functions.
