### ISSUE TITLE
[CODE] Unable to compile due to float conversion to soundlevel_t

### ISSUE THREAD

**Issue by MidnightDragons** [mapbase-source/source-sdk-2013#288]
### Describe the bug
I am unable to compile mapbase due to an error with float conversions to soundlevel_t. Is this a common issue or is there something I am doing wrong?

This error specifically shows up:
error C2440: '<function-style-cast>' : cannot convert from 'float' to 'soundlevel_t'	c:\users\treet\all_folders\po3-master\sp\src\public\soundflags.h

### Steps to reproduce
1. Fork and clone git
2. Try to compile
3. See error

### Expected behavior
Supposed to compile. I have made no changes to the original.

**Comment by Blixibon** [comment]
This appears to be a Visual Studio 2013-specific issue which came from a Mapbase v7.2 change fixing some GCC warnings. Since our build automation systems use Visual Studio 2022, compilation on Visual Studio 2013 wasn't tested before release.

Does it work after pulling the latest changes from `master`?

**Comment by MidnightDragons** [comment]
That seemed to have fixed it, thank you!!
